name: Lint and Test

on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  standard-checks:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install packages
        run: npm ci
        
      - name: Run ESlint
        run: npm run lint

      - name: Run Jest
        run: npm run test